* initramfs-tools-hook: Warn when files needed by network hooks are                         not found.

diff --git a/initramfs-tools-hook b/initramfs-tools-hook
--- a/initramfs-tools-hook
+++ b/initramfs-tools-hook
@@ -118,6 +118,9 @@ for hook in /etc/mandos/network-hooks.d/*; do
         # Copy any files needed by the network hook
 	MANDOSNETHOOKDIR=/etc/mandos/network-hooks.d MODE=files \
 	    VERBOSITY=0 "$hook" files | while read file target; do
+	    if [ ! -e "${file}" ]; then
+		echo "WARNING: file ${file} not found, requested by Mandos network hook '${hook##*/}'" >&2
+	    fi
 	    if [ -z "${target}" ]; then
 		copy_exec "$file"
 	    else
